# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
language: cpp
compiler: 
    - clang
    - gcc
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.8"; fi
before_script:
    - mkdir build
    - cd build
    - cmake -DBuildSubmodules=On ..
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang-3.8
    - lldb-3.8

script: make check
